name: Run python
on:
    push:
    schedule:
        - cron: 0 0 * * * #every end of day
jobs:
     build:
         name: set and run
         runs-on: ubuntu-last
         steps:
              -uses: actions/checkout@V
              -name: step1
              run: |
                python3 main.py